In [1]:
from scipy.io import loadmat

In [2]:
eeg_emg_bands = loadmat('sample_data.mat')

In [3]:
eeg_emg_bands.keys()

dict_keys(['__header__', '__version__', '__globals__', 'epochTime', 'd', 'bandsD', 'epochsLinked'])

In [4]:
eeg_emg_bands['d'];

In [5]:
len(eeg_emg_bands['d'])

36432

In [6]:
len(eeg_emg_bands['d'][0])

11

In [7]:
eeg_emg_bands['epochsLinked']

array([[    0,     0,     1,    61],
       [    1,     1,     1,    61],
       [    2,     2,     1,    61],
       ...,
       [16197, 37407,     2,    61],
       [16198, 37408,     2,    61],
       [16199, 37409,     2,    61]], dtype=int32)

In [8]:
len(eeg_emg_bands['epochsLinked'])

36432

In [9]:
eeg_emg_bands['epochTime'].dtype

dtype('<f8')

In [10]:
(eeg_emg_bands['epochTime'][36431][2] - eeg_emg_bands['epochTime'][0][2]) / 36432

8.234392028162487e-05

In [11]:
len(eeg_emg_bands['epochTime'])

36432

In [12]:
lfp_buz_features = loadmat('../rgs14/lfp_buz_features_rgs14.mat')

In [13]:
lfp_buz_features.keys()

dict_keys(['__header__', '__version__', '__globals__', 'lfpFeatures'])

In [14]:
import pandas as pd
import numpy as np

lfp_matrix = np.array(lfp_buz_features['lfpFeatures'])

numColumns = len(lfp_matrix[0])

delta_pfc_df = pd.DataFrame(lfp_matrix[:, 0], columns=["DeltaPFC"])
theta_hpc_df = pd.DataFrame(lfp_matrix[:, 1], columns=["ThetaHPC"])
beta_pfc_df = pd.DataFrame(lfp_matrix[:, 2], columns=["BetaPFC"])
gamma_hpc_df = pd.DataFrame(lfp_matrix[:, 3], columns=["GammaHPC"])
emg_like_df = pd.DataFrame(lfp_matrix[:, 4], columns=["EMGLike"])

timesteps = 4216

In [15]:
delta_pfc_theta_hpc = delta_pfc_df['DeltaPFC'] / theta_hpc_df['ThetaHPC']
delta_pfc_beta_pfc  = delta_pfc_df['DeltaPFC'] / beta_pfc_df['BetaPFC']
delta_pfc_gamma_hpc = delta_pfc_df['DeltaPFC'] / gamma_hpc_df['GammaHPC']
theta_hpc_beta_pfc  = theta_hpc_df['ThetaHPC'] / beta_pfc_df['BetaPFC']
theta_hpc_gamma_hpc = theta_hpc_df['ThetaHPC'] / gamma_hpc_df['GammaHPC']
beta_pfc_gamma_hpc  = beta_pfc_df['BetaPFC'] / gamma_hpc_df['GammaHPC']

In [16]:
eeg_emg_bands['d'].shape

(36432, 11)

In [17]:
rgs_14_bands = np.column_stack([
    delta_pfc_theta_hpc, 
    delta_pfc_beta_pfc, 
    delta_pfc_gamma_hpc, 
    theta_hpc_beta_pfc, 
    theta_hpc_gamma_hpc,
    beta_pfc_gamma_hpc,
    emg_like_df.EMGLike
])

In [18]:
rgs_14_bands

array([[0.36091171, 0.48330075, 0.47004354, ..., 1.30237819, 0.97256945,
        0.8007592 ],
       [0.44655373, 0.58461009, 0.5890688 , ..., 1.31914428, 1.00762681,
        0.79285198],
       [0.54187165, 0.69228439, 0.72560372, ..., 1.33906936, 1.04812954,
        0.80440521],
       ...,
       [6.28698113, 0.84385264, 0.42591768, ..., 0.06774598, 0.50472993,
        0.07370505],
       [6.97536932, 0.74219795, 0.38028943, ..., 0.0545189 , 0.51238276,
        0.09134548],
       [8.22567374, 0.64598561, 0.33922455, ..., 0.04123973, 0.52512709,
        0.09731904]])

In [19]:
rgs_14_bands.dtype

dtype('float64')

In [20]:
eeg_emg_bands['d']

array([[-0.7700516 , -0.3760239 , -0.683785  , ..., -0.5382018 ,
        -0.23044461,  0.19272518],
       [ 0.7632049 ,  0.43585336,  0.1796093 , ..., -0.87780964,
        -0.62156934,  0.10145473],
       [-0.00528526,  0.23130655, -0.25944912, ..., -0.02930842,
         0.46144333,  0.49312115],
       ...,
       [ 0.21864802,  0.40962934,  0.10500968, ...,  0.50173366,
         0.8063495 , -0.62143993],
       [ 0.35620993, -0.19546735,  0.3797109 , ...,  0.9357698 ,
         0.36058757, -0.62169456],
       [-0.08637416, -1.0785775 , -0.44793767, ...,  1.3306514 ,
         0.7000077 , -0.64962673]], dtype=float32)

In [21]:
eeg_emg_bands['epochsLinked']

array([[    0,     0,     1,    61],
       [    1,     1,     1,    61],
       [    2,     2,     1,    61],
       ...,
       [16197, 37407,     2,    61],
       [16198, 37408,     2,    61],
       [16199, 37409,     2,    61]], dtype=int32)

In [22]:
len(eeg_emg_bands['epochsLinked'])

36432

In [23]:
eeg_emg_bands['epochsLinked'].shape

(36432, 4)

In [24]:
eeg_emg_bands['epochsLinked']

array([[    0,     0,     1,    61],
       [    1,     1,     1,    61],
       [    2,     2,     1,    61],
       ...,
       [16197, 37407,     2,    61],
       [16198, 37408,     2,    61],
       [16199, 37409,     2,    61]], dtype=int32)

In [25]:
eeg_emg_bands['epochsLinked'][0]

array([ 0,  0,  1, 61], dtype=int32)

In [26]:
epoch_ids = np.arange(4216)

In [27]:
epoch_ids

array([   0,    1,    2, ..., 4213, 4214, 4215])